export const enum UI_Event {
  DISABLE_ALL_BUTTONS = 'UIEvent_DISABLE_ALL_BUTTONS',
  DISABLE_UI_ELEMENT_ = 'UIEvent_DISABLE_BUTTON_',
  ENABLE_UI_ELEMENT_ = 'UIEvent_ENABLE_BUTTON_',
  UPDATE_TEXT_AT_ELEMENT_ = 'UIEvent_UPDATE_TEXT_AT_ELEMENT_',
  HIDE_BASE_UI = 'UIEvent_HIDE_BASE_UI',
  SHOW_BASE_UI = 'UIEvent_SHOW_BASE_UI',
}

export const enum UIElementName {
  DEAL = 'UIElementName_DEAL',
  DECREASE_STAKE = 'UIElementName_DECREASE_STAKE',
  INCREASE_STAKE = 'UIElementName_INCREASE_STAKE',
  ALL_IN = 'UIElementName_ALL_IN',
  STAND = 'UIElementName_STAND',
  DOUBLE = 'UIElementName_DOUBLE',
  HIT = 'UIElementName_HIT',
  SHOP = 'UIElementName_SHOP',
  PLAYER_BALANCE = 'UIElementName_PLAYER_BALANCE',
  DEALER_BALANCE = 'UIElementName_DEALER_BALANCE',
  SHOP_BACK = 'UIElementName_SHOP_BACK',
  SHOP_SUBMIT = 'UIElementName_SHOP_SUBMIT',
  SHOP_CANCEL = 'UIElementName_SHOP_CANCEL',
  SHOP_BULLET_INFO = 'UIElementName_SHOP_BULLET_INFO',
  SHOP_BUY_BAD = 'UIElementName_SHOP_BUY_BAD',
  SHOP_BUY_SO_SO = 'UIElementName_SHOP_BUY_SHOP_SHOP_BUY_SO_SO',
  SHOP_BUY_GOOD = 'UIElementName_SHOP_BUY_GOOD',
}
